baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Threat-Actors.com'
theme = 'threatactorstheme'

[[menu.main]]
    name = "Ransomware Groups"
    url = "/ransomwaregroups"
    weight = 1

[[menu.main]]
    name = "Illegal Forums"
    url = "/forums"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/Sh0ckFR"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/Sh0ckFR"
    pre = "<i class='fab fa-twitter'></i>"